-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity morphology is
generic (
    C_S_AXI_CTRL_ADDR_WIDTH : INTEGER := 5;
    C_S_AXI_CTRL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    in_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    in_stream_TVALID : IN STD_LOGIC;
    in_stream_TREADY : OUT STD_LOGIC;
    in_stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_stream_TVALID : OUT STD_LOGIC;
    out_stream_TREADY : IN STD_LOGIC;
    out_stream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    s_axi_CTRL_AWVALID : IN STD_LOGIC;
    s_axi_CTRL_AWREADY : OUT STD_LOGIC;
    s_axi_CTRL_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_WVALID : IN STD_LOGIC;
    s_axi_CTRL_WREADY : OUT STD_LOGIC;
    s_axi_CTRL_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH/8-1 downto 0);
    s_axi_CTRL_ARVALID : IN STD_LOGIC;
    s_axi_CTRL_ARREADY : OUT STD_LOGIC;
    s_axi_CTRL_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_RVALID : OUT STD_LOGIC;
    s_axi_CTRL_RREADY : IN STD_LOGIC;
    s_axi_CTRL_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_CTRL_BVALID : OUT STD_LOGIC;
    s_axi_CTRL_BREADY : IN STD_LOGIC;
    s_axi_CTRL_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of morphology is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "morphology_morphology,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.031000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=958,HLS_SYN_LUT=936,HLS_VERSION=2022_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal width : STD_LOGIC_VECTOR (31 downto 0);
    signal height : STD_LOGIC_VECTOR (31 downto 0);
    signal height_read_reg_122 : STD_LOGIC_VECTOR (31 downto 0);
    signal width_read_reg_127 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_fu_116_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal mul_ln9_reg_143 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal line_buf0_V_q1 : STD_LOGIC_VECTOR (7 downto 0);
    signal line_buf1_V_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_ap_start : STD_LOGIC;
    signal grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_ap_done : STD_LOGIC;
    signal grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_ap_idle : STD_LOGIC;
    signal grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_ap_ready : STD_LOGIC;
    signal grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_out_stream_TREADY : STD_LOGIC;
    signal grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_in_stream_TREADY : STD_LOGIC;
    signal grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf0_V_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf0_V_ce0 : STD_LOGIC;
    signal grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf0_V_we0 : STD_LOGIC;
    signal grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf0_V_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf0_V_address1 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf0_V_ce1 : STD_LOGIC;
    signal grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf1_V_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf1_V_ce0 : STD_LOGIC;
    signal grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf1_V_we0 : STD_LOGIC;
    signal grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf1_V_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_out_stream_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_out_stream_TVALID : STD_LOGIC;
    signal grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_out_stream_TKEEP : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_out_stream_TSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_out_stream_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_ap_start_reg : STD_LOGIC := '0';
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_NS_fsm_state4 : STD_LOGIC;
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_fu_116_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_116_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal regslice_both_out_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal regslice_both_in_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal in_stream_TVALID_int_regslice : STD_LOGIC;
    signal in_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_in_stream_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_in_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_in_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_last_V_U_ack_in : STD_LOGIC;
    signal out_stream_TVALID_int_regslice : STD_LOGIC;
    signal out_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_out_stream_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal grp_fu_116_p00 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_116_p10 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component morphology_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_stream_TVALID : IN STD_LOGIC;
        out_stream_TREADY : IN STD_LOGIC;
        width : IN STD_LOGIC_VECTOR (31 downto 0);
        mul_ln9 : IN STD_LOGIC_VECTOR (63 downto 0);
        in_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        in_stream_TREADY : OUT STD_LOGIC;
        in_stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        in_stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        line_buf0_V_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        line_buf0_V_ce0 : OUT STD_LOGIC;
        line_buf0_V_we0 : OUT STD_LOGIC;
        line_buf0_V_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        line_buf0_V_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
        line_buf0_V_ce1 : OUT STD_LOGIC;
        line_buf0_V_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
        line_buf1_V_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        line_buf1_V_ce0 : OUT STD_LOGIC;
        line_buf1_V_we0 : OUT STD_LOGIC;
        line_buf1_V_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        line_buf1_V_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        out_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_stream_TVALID : OUT STD_LOGIC;
        out_stream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
        out_stream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component morphology_mul_32ns_32ns_64_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component morphology_line_buf0_V_RAM_T2P_BRAM_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (7 downto 0);
        address1 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component morphology_line_buf1_V_RAM_T2P_BRAM_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (7 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component morphology_CTRL_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        width : OUT STD_LOGIC_VECTOR (31 downto 0);
        height : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component morphology_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    line_buf0_V_U : component morphology_line_buf0_V_RAM_T2P_BRAM_1R1W
    generic map (
        DataWidth => 8,
        AddressRange => 320,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf0_V_address0,
        ce0 => grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf0_V_ce0,
        we0 => grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf0_V_we0,
        d0 => grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf0_V_d0,
        address1 => grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf0_V_address1,
        ce1 => grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf0_V_ce1,
        q1 => line_buf0_V_q1);

    line_buf1_V_U : component morphology_line_buf1_V_RAM_T2P_BRAM_1R1W
    generic map (
        DataWidth => 8,
        AddressRange => 320,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf1_V_address0,
        ce0 => grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf1_V_ce0,
        we0 => grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf1_V_we0,
        d0 => grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf1_V_d0,
        q0 => line_buf1_V_q0);

    grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86 : component morphology_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_ap_start,
        ap_done => grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_ap_done,
        ap_idle => grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_ap_idle,
        ap_ready => grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_ap_ready,
        in_stream_TVALID => in_stream_TVALID_int_regslice,
        out_stream_TREADY => grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_out_stream_TREADY,
        width => width_read_reg_127,
        mul_ln9 => mul_ln9_reg_143,
        in_stream_TDATA => in_stream_TDATA_int_regslice,
        in_stream_TREADY => grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_in_stream_TREADY,
        in_stream_TKEEP => in_stream_TKEEP_int_regslice,
        in_stream_TSTRB => in_stream_TSTRB_int_regslice,
        in_stream_TLAST => in_stream_TLAST_int_regslice,
        line_buf0_V_address0 => grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf0_V_address0,
        line_buf0_V_ce0 => grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf0_V_ce0,
        line_buf0_V_we0 => grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf0_V_we0,
        line_buf0_V_d0 => grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf0_V_d0,
        line_buf0_V_address1 => grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf0_V_address1,
        line_buf0_V_ce1 => grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf0_V_ce1,
        line_buf0_V_q1 => line_buf0_V_q1,
        line_buf1_V_address0 => grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf1_V_address0,
        line_buf1_V_ce0 => grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf1_V_ce0,
        line_buf1_V_we0 => grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf1_V_we0,
        line_buf1_V_d0 => grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf1_V_d0,
        line_buf1_V_q0 => line_buf1_V_q0,
        out_stream_TDATA => grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_out_stream_TDATA,
        out_stream_TVALID => grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_out_stream_TVALID,
        out_stream_TKEEP => grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_out_stream_TKEEP,
        out_stream_TSTRB => grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_out_stream_TSTRB,
        out_stream_TLAST => grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_out_stream_TLAST);

    CTRL_s_axi_U : component morphology_CTRL_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CTRL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CTRL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_CTRL_AWVALID,
        AWREADY => s_axi_CTRL_AWREADY,
        AWADDR => s_axi_CTRL_AWADDR,
        WVALID => s_axi_CTRL_WVALID,
        WREADY => s_axi_CTRL_WREADY,
        WDATA => s_axi_CTRL_WDATA,
        WSTRB => s_axi_CTRL_WSTRB,
        ARVALID => s_axi_CTRL_ARVALID,
        ARREADY => s_axi_CTRL_ARREADY,
        ARADDR => s_axi_CTRL_ARADDR,
        RVALID => s_axi_CTRL_RVALID,
        RREADY => s_axi_CTRL_RREADY,
        RDATA => s_axi_CTRL_RDATA,
        RRESP => s_axi_CTRL_RRESP,
        BVALID => s_axi_CTRL_BVALID,
        BREADY => s_axi_CTRL_BREADY,
        BRESP => s_axi_CTRL_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        width => width,
        height => height,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    mul_32ns_32ns_64_2_1_U13 : component morphology_mul_32ns_32ns_64_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_116_p0,
        din1 => grp_fu_116_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_116_p2);

    regslice_both_in_stream_V_data_V_U : component morphology_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TDATA,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_data_V_U_ack_in,
        data_out => in_stream_TDATA_int_regslice,
        vld_out => in_stream_TVALID_int_regslice,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_data_V_U_apdone_blk);

    regslice_both_in_stream_V_keep_V_U : component morphology_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TKEEP,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_keep_V_U_ack_in,
        data_out => in_stream_TKEEP_int_regslice,
        vld_out => regslice_both_in_stream_V_keep_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_keep_V_U_apdone_blk);

    regslice_both_in_stream_V_strb_V_U : component morphology_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TSTRB,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_strb_V_U_ack_in,
        data_out => in_stream_TSTRB_int_regslice,
        vld_out => regslice_both_in_stream_V_strb_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_strb_V_U_apdone_blk);

    regslice_both_in_stream_V_last_V_U : component morphology_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TLAST,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_last_V_U_ack_in,
        data_out => in_stream_TLAST_int_regslice,
        vld_out => regslice_both_in_stream_V_last_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_last_V_U_apdone_blk);

    regslice_both_out_stream_V_data_V_U : component morphology_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_out_stream_TDATA,
        vld_in => grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_out_stream_TVALID,
        ack_in => out_stream_TREADY_int_regslice,
        data_out => out_stream_TDATA,
        vld_out => regslice_both_out_stream_V_data_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_data_V_U_apdone_blk);

    regslice_both_out_stream_V_keep_V_U : component morphology_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_out_stream_TKEEP,
        vld_in => grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_out_stream_TVALID,
        ack_in => regslice_both_out_stream_V_keep_V_U_ack_in_dummy,
        data_out => out_stream_TKEEP,
        vld_out => regslice_both_out_stream_V_keep_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_keep_V_U_apdone_blk);

    regslice_both_out_stream_V_strb_V_U : component morphology_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_out_stream_TSTRB,
        vld_in => grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_out_stream_TVALID,
        ack_in => regslice_both_out_stream_V_strb_V_U_ack_in_dummy,
        data_out => out_stream_TSTRB,
        vld_out => regslice_both_out_stream_V_strb_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_strb_V_U_apdone_blk);

    regslice_both_out_stream_V_last_V_U : component morphology_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_out_stream_TLAST,
        vld_in => grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_out_stream_TVALID,
        ack_in => regslice_both_out_stream_V_last_V_U_ack_in_dummy,
        data_out => out_stream_TLAST,
        vld_out => regslice_both_out_stream_V_last_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_logic_1 = ap_NS_fsm_state4))) then 
                    grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_ap_ready = ap_const_logic_1)) then 
                    grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                height_read_reg_122 <= height;
                width_read_reg_127 <= width;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                mul_ln9_reg_143 <= grp_fu_116_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_ap_done, ap_CS_fsm_state5, ap_CS_fsm_state6, regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_NS_fsm_state4 <= ap_NS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_ap_done)
    begin
        if ((grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state6_blk_assign_proc : process(regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if ((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_1)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state6, regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) and (regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state6, regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) and (regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    grp_fu_116_p0 <= grp_fu_116_p00(32 - 1 downto 0);
    grp_fu_116_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(height_read_reg_122),64));
    grp_fu_116_p1 <= grp_fu_116_p10(32 - 1 downto 0);
    grp_fu_116_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(width_read_reg_127),64));
    grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_ap_start <= grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_ap_start_reg;
    grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_out_stream_TREADY <= (out_stream_TREADY_int_regslice and ap_CS_fsm_state5);
    in_stream_TREADY <= regslice_both_in_stream_V_data_V_U_ack_in;

    in_stream_TREADY_int_regslice_assign_proc : process(grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_in_stream_TREADY, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            in_stream_TREADY_int_regslice <= grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_in_stream_TREADY;
        else 
            in_stream_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    out_stream_TVALID <= regslice_both_out_stream_V_data_V_U_vld_out;
    out_stream_TVALID_int_regslice <= grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_out_stream_TVALID;
end behav;
