-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity morphology_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_stream_TVALID : IN STD_LOGIC;
    out_stream_TREADY : IN STD_LOGIC;
    width : IN STD_LOGIC_VECTOR (31 downto 0);
    mul_ln9 : IN STD_LOGIC_VECTOR (63 downto 0);
    in_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    in_stream_TREADY : OUT STD_LOGIC;
    in_stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    line_buf0_V_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    line_buf0_V_ce0 : OUT STD_LOGIC;
    line_buf0_V_we0 : OUT STD_LOGIC;
    line_buf0_V_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    line_buf0_V_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    line_buf0_V_ce1 : OUT STD_LOGIC;
    line_buf0_V_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    line_buf1_V_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    line_buf1_V_ce0 : OUT STD_LOGIC;
    line_buf1_V_we0 : OUT STD_LOGIC;
    line_buf1_V_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    line_buf1_V_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    out_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_stream_TVALID : OUT STD_LOGIC;
    out_stream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of morphology_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_FFFFFFFFFFFFFFFF : STD_LOGIC_VECTOR (63 downto 0) := "1111111111111111111111111111111111111111111111111111111111111111";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv30_0 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000000000000000";
    constant ap_const_lv32_FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln29_fu_267_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal in_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal out_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln30_fu_262_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln30_reg_715 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln30_reg_715_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln30_reg_715_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln29_reg_721 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln29_reg_721_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_reg_725 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_reg_725_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_reg_725_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal val_V_1_fu_300_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal val_V_1_reg_730 : STD_LOGIC_VECTOR (7 downto 0);
    signal line_buf0_V_addr_reg_737 : STD_LOGIC_VECTOR (8 downto 0);
    signal line_buf0_V_addr_reg_737_pp0_iter2_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal addr_cmp22_fu_308_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal addr_cmp22_reg_743 : STD_LOGIC_VECTOR (0 downto 0);
    signal addr_cmp22_reg_743_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal addr_cmp_fu_317_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal addr_cmp_reg_753 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln60_fu_343_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln60_reg_758 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln60_reg_758_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln60_reg_758_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal reuse_select_fu_374_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal reuse_select_reg_763 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln1069_6_fu_385_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1069_6_reg_771 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1069_6_reg_771_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1069_7_fu_391_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1069_7_reg_776 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1069_7_reg_776_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1069_8_fu_397_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1069_8_reg_781 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1069_8_reg_781_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1069_5_fu_467_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1069_5_reg_786 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln54_6_fu_490_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln54_6_reg_791 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter3_stage0 : STD_LOGIC;
    signal zext_ln30_fu_286_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal reuse_addr_reg19_fu_94 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal reuse_reg18_fu_98 : STD_LOGIC_VECTOR (7 downto 0);
    signal reuse_addr_reg_fu_102 : STD_LOGIC_VECTOR (63 downto 0);
    signal reuse_reg_fu_106 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_0_076307_fu_110 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_0_074309_fu_114 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_0_072311_fu_118 : STD_LOGIC_VECTOR (7 downto 0);
    signal x_fu_122 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln30_fu_349_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal y_fu_126 : STD_LOGIC_VECTOR (30 downto 0);
    signal select_ln29_2_fu_563_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal indvar_flatten_fu_130 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln29_fu_272_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_0_0_075308_fu_134 : STD_LOGIC_VECTOR (7 downto 0);
    signal reuse_select23_fu_426_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_0_073310_fu_138 : STD_LOGIC_VECTOR (7 downto 0);
    signal val_V_fu_142 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal zext_ln30_1_fu_258_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln29_fu_278_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_2_fu_333_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln1069_1_fu_443_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1069_2_fu_449_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1069_4_fu_461_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1069_fu_437_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln54_4_fu_478_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1069_3_fu_455_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln54_5_fu_484_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln54_3_fu_472_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln29_1_fu_518_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_fu_524_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_1_fu_540_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal icmp_fu_534_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp14_fu_550_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln54_1_fu_574_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln54_fu_570_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln54_2_fu_578_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln54_7_fu_584_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln29_1_fu_556_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal valid_fu_595_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_val_V_fu_589_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_data_V_fu_600_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component morphology_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component morphology_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter3_stage0)) then 
                    ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten_fu_130_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_130 <= ap_const_lv64_0;
                elsif (((icmp_ln29_fu_267_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    indvar_flatten_fu_130 <= add_ln29_fu_272_p2;
                end if;
            end if; 
        end if;
    end process;

    reuse_addr_reg19_fu_94_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    reuse_addr_reg19_fu_94 <= ap_const_lv64_FFFFFFFFFFFFFFFF;
                elsif (((icmp_ln29_fu_267_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    reuse_addr_reg19_fu_94 <= zext_ln30_fu_286_p1;
                end if;
            end if; 
        end if;
    end process;

    reuse_addr_reg_fu_102_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    reuse_addr_reg_fu_102 <= ap_const_lv64_FFFFFFFFFFFFFFFF;
                elsif (((icmp_ln29_fu_267_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    reuse_addr_reg_fu_102 <= zext_ln30_fu_286_p1;
                end if;
            end if; 
        end if;
    end process;

    reuse_reg18_fu_98_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    reuse_reg18_fu_98 <= ap_const_lv8_0;
                elsif (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (icmp_ln29_reg_721_pp0_iter2_reg = ap_const_lv1_0))) then 
                    reuse_reg18_fu_98 <= reuse_select_reg_763;
                end if;
            end if; 
        end if;
    end process;

    reuse_reg_fu_106_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    reuse_reg_fu_106 <= ap_const_lv8_0;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln29_reg_721 = ap_const_lv1_0))) then 
                    reuse_reg_fu_106 <= val_V_1_reg_730;
                end if;
            end if; 
        end if;
    end process;

    x_fu_122_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    x_fu_122 <= ap_const_lv9_0;
                elsif (((icmp_ln29_fu_267_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    x_fu_122 <= add_ln30_fu_349_p2;
                end if;
            end if; 
        end if;
    end process;

    y_fu_126_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    y_fu_126 <= ap_const_lv31_0;
                elsif ((ap_enable_reg_pp0_iter4 = ap_const_logic_1)) then 
                    y_fu_126 <= select_ln29_2_fu_563_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln29_fu_267_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                addr_cmp22_reg_743 <= addr_cmp22_fu_308_p2;
                addr_cmp_reg_753 <= addr_cmp_fu_317_p2;
                icmp_ln60_reg_758 <= icmp_ln60_fu_343_p2;
                line_buf0_V_addr_reg_737 <= zext_ln30_fu_286_p1(9 - 1 downto 0);
                tmp_last_V_reg_725 <= in_stream_TLAST;
                val_V_1_reg_730 <= val_V_1_fu_300_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                addr_cmp22_reg_743_pp0_iter2_reg <= addr_cmp22_reg_743;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                icmp_ln1069_6_reg_771_pp0_iter3_reg <= icmp_ln1069_6_reg_771;
                icmp_ln1069_7_reg_776_pp0_iter3_reg <= icmp_ln1069_7_reg_776;
                icmp_ln1069_8_reg_781_pp0_iter3_reg <= icmp_ln1069_8_reg_781;
                icmp_ln29_reg_721_pp0_iter2_reg <= icmp_ln29_reg_721;
                icmp_ln30_reg_715_pp0_iter2_reg <= icmp_ln30_reg_715;
                icmp_ln30_reg_715_pp0_iter3_reg <= icmp_ln30_reg_715_pp0_iter2_reg;
                icmp_ln60_reg_758_pp0_iter2_reg <= icmp_ln60_reg_758;
                icmp_ln60_reg_758_pp0_iter3_reg <= icmp_ln60_reg_758_pp0_iter2_reg;
                line_buf0_V_addr_reg_737_pp0_iter2_reg <= line_buf0_V_addr_reg_737;
                tmp_last_V_reg_725_pp0_iter2_reg <= tmp_last_V_reg_725;
                tmp_last_V_reg_725_pp0_iter3_reg <= tmp_last_V_reg_725_pp0_iter2_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
                icmp_ln29_reg_721 <= icmp_ln29_fu_267_p2;
                icmp_ln30_reg_715 <= icmp_ln30_fu_262_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln29_reg_721_pp0_iter2_reg = ap_const_lv1_0))) then
                icmp_ln1069_5_reg_786 <= icmp_ln1069_5_fu_467_p2;
                or_ln54_6_reg_791 <= or_ln54_6_fu_490_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln29_reg_721 = ap_const_lv1_0))) then
                icmp_ln1069_6_reg_771 <= icmp_ln1069_6_fu_385_p2;
                icmp_ln1069_7_reg_776 <= icmp_ln1069_7_fu_391_p2;
                icmp_ln1069_8_reg_781 <= icmp_ln1069_8_fu_397_p2;
                reuse_select_reg_763 <= reuse_select_fu_374_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln29_reg_721 = ap_const_lv1_0))) then
                p_0_0_072311_fu_118 <= val_V_fu_142;
                val_V_fu_142 <= val_V_1_reg_730;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (icmp_ln29_reg_721_pp0_iter2_reg = ap_const_lv1_0))) then
                p_0_0_073310_fu_138 <= reuse_select_reg_763;
                p_0_0_074309_fu_114 <= p_0_0_073310_fu_138;
                p_0_0_075308_fu_134 <= reuse_select23_fu_426_p3;
                p_0_0_076307_fu_110 <= p_0_0_075308_fu_134;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln29_1_fu_518_p2 <= std_logic_vector(unsigned(y_fu_126) + unsigned(ap_const_lv31_1));
    add_ln29_fu_272_p2 <= std_logic_vector(unsigned(indvar_flatten_fu_130) + unsigned(ap_const_lv64_1));
    add_ln30_fu_349_p2 <= std_logic_vector(unsigned(select_ln29_fu_278_p3) + unsigned(ap_const_lv9_1));
    addr_cmp22_fu_308_p2 <= "1" when (reuse_addr_reg19_fu_94 = zext_ln30_fu_286_p1) else "0";
    addr_cmp_fu_317_p2 <= "1" when (reuse_addr_reg_fu_102 = zext_ln30_fu_286_p1) else "0";
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter4, in_stream_TVALID, icmp_ln29_fu_267_p2, out_stream_TREADY)
    begin
                ap_block_pp0_stage0_01001 <= (((out_stream_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)) or ((icmp_ln29_fu_267_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter4, in_stream_TVALID, icmp_ln29_fu_267_p2, out_stream_TREADY)
    begin
                ap_block_pp0_stage0_11001 <= (((out_stream_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)) or ((icmp_ln29_fu_267_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter4, in_stream_TVALID, icmp_ln29_fu_267_p2, out_stream_TREADY)
    begin
                ap_block_pp0_stage0_subdone <= (((out_stream_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)) or ((icmp_ln29_fu_267_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state2_pp0_stage0_iter1_assign_proc : process(in_stream_TVALID, icmp_ln29_fu_267_p2)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((icmp_ln29_fu_267_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0));
    end process;

        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state5_pp0_stage0_iter4_assign_proc : process(out_stream_TREADY)
    begin
                ap_block_state5_pp0_stage0_iter4 <= (out_stream_TREADY = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln29_fu_267_p2, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln29_fu_267_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter3_stage0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_subdone, icmp_ln29_reg_721_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (icmp_ln29_reg_721_pp0_iter2_reg = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter3_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter3_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    icmp14_fu_550_p2 <= "0" when (tmp_1_fu_540_p4 = ap_const_lv30_0) else "1";
    icmp_fu_534_p2 <= "0" when (tmp_fu_524_p4 = ap_const_lv30_0) else "1";
    icmp_ln1069_1_fu_443_p2 <= "0" when (p_0_0_075308_fu_134 = ap_const_lv8_FF) else "1";
    icmp_ln1069_2_fu_449_p2 <= "0" when (reuse_select23_fu_426_p3 = ap_const_lv8_FF) else "1";
    icmp_ln1069_3_fu_455_p2 <= "0" when (p_0_0_074309_fu_114 = ap_const_lv8_FF) else "1";
    icmp_ln1069_4_fu_461_p2 <= "0" when (p_0_0_073310_fu_138 = ap_const_lv8_FF) else "1";
    icmp_ln1069_5_fu_467_p2 <= "0" when (reuse_select_reg_763 = ap_const_lv8_FF) else "1";
    icmp_ln1069_6_fu_385_p2 <= "0" when (p_0_0_072311_fu_118 = ap_const_lv8_FF) else "1";
    icmp_ln1069_7_fu_391_p2 <= "0" when (val_V_fu_142 = ap_const_lv8_FF) else "1";
    icmp_ln1069_8_fu_397_p2 <= "0" when (val_V_1_reg_730 = ap_const_lv8_FF) else "1";
    icmp_ln1069_fu_437_p2 <= "0" when (p_0_0_076307_fu_110 = ap_const_lv8_FF) else "1";
    icmp_ln29_fu_267_p2 <= "1" when (indvar_flatten_fu_130 = mul_ln9) else "0";
    icmp_ln30_fu_262_p2 <= "1" when (zext_ln30_1_fu_258_p1 = width) else "0";
    icmp_ln60_fu_343_p2 <= "0" when (tmp_2_fu_333_p4 = ap_const_lv8_0) else "1";

    in_stream_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, in_stream_TVALID, icmp_ln29_fu_267_p2, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln29_fu_267_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_stream_TDATA_blk_n <= in_stream_TVALID;
        else 
            in_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    in_stream_TREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln29_fu_267_p2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln29_fu_267_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_stream_TREADY <= ap_const_logic_1;
        else 
            in_stream_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    line_buf0_V_address0 <= line_buf0_V_addr_reg_737_pp0_iter2_reg;
    line_buf0_V_address1 <= line_buf0_V_addr_reg_737;

    line_buf0_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            line_buf0_V_ce0 <= ap_const_logic_1;
        else 
            line_buf0_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buf0_V_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            line_buf0_V_ce1 <= ap_const_logic_1;
        else 
            line_buf0_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    line_buf0_V_d0 <= reuse_select_reg_763;

    line_buf0_V_we0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001, icmp_ln29_reg_721_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (icmp_ln29_reg_721_pp0_iter2_reg = ap_const_lv1_0))) then 
            line_buf0_V_we0 <= ap_const_logic_1;
        else 
            line_buf0_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    line_buf1_V_address0 <= zext_ln30_fu_286_p1(9 - 1 downto 0);

    line_buf1_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln29_fu_267_p2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln29_fu_267_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            line_buf1_V_ce0 <= ap_const_logic_1;
        else 
            line_buf1_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    line_buf1_V_d0 <= in_stream_TDATA(8 - 1 downto 0);

    line_buf1_V_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln29_fu_267_p2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln29_fu_267_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            line_buf1_V_we0 <= ap_const_logic_1;
        else 
            line_buf1_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    or_ln54_1_fu_574_p2 <= (icmp_ln1069_6_reg_771_pp0_iter3_reg or icmp_ln1069_5_reg_786);
    or_ln54_2_fu_578_p2 <= (or_ln54_fu_570_p2 or or_ln54_1_fu_574_p2);
    or_ln54_3_fu_472_p2 <= (icmp_ln1069_2_fu_449_p2 or icmp_ln1069_1_fu_443_p2);
    or_ln54_4_fu_478_p2 <= (icmp_ln1069_fu_437_p2 or icmp_ln1069_4_fu_461_p2);
    or_ln54_5_fu_484_p2 <= (or_ln54_4_fu_478_p2 or icmp_ln1069_3_fu_455_p2);
    or_ln54_6_fu_490_p2 <= (or_ln54_5_fu_484_p2 or or_ln54_3_fu_472_p2);
    or_ln54_7_fu_584_p2 <= (or_ln54_6_reg_791 or or_ln54_2_fu_578_p2);
    or_ln54_fu_570_p2 <= (icmp_ln1069_8_reg_781_pp0_iter3_reg or icmp_ln1069_7_reg_776_pp0_iter3_reg);
    out_data_V_fu_600_p2 <= (valid_fu_595_p2 and out_val_V_fu_589_p2);
    out_stream_TDATA <= 
        ap_const_lv32_FF when (out_data_V_fu_600_p2(0) = '1') else 
        ap_const_lv32_0;

    out_stream_TDATA_blk_n_assign_proc : process(ap_enable_reg_pp0_iter4, out_stream_TREADY, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            out_stream_TDATA_blk_n <= out_stream_TREADY;
        else 
            out_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_stream_TKEEP <= ap_const_lv4_F;
    out_stream_TLAST <= tmp_last_V_reg_725_pp0_iter3_reg;
    out_stream_TSTRB <= ap_const_lv4_F;

    out_stream_TVALID_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            out_stream_TVALID <= ap_const_logic_1;
        else 
            out_stream_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    out_val_V_fu_589_p2 <= (or_ln54_7_fu_584_p2 xor ap_const_lv1_1);
    reuse_select23_fu_426_p3 <= 
        reuse_reg18_fu_98 when (addr_cmp22_reg_743_pp0_iter2_reg(0) = '1') else 
        line_buf0_V_q1;
    reuse_select_fu_374_p3 <= 
        reuse_reg_fu_106 when (addr_cmp_reg_753(0) = '1') else 
        line_buf1_V_q0;
    select_ln29_1_fu_556_p3 <= 
        icmp_fu_534_p2 when (icmp_ln30_reg_715_pp0_iter3_reg(0) = '1') else 
        icmp14_fu_550_p2;
    select_ln29_2_fu_563_p3 <= 
        add_ln29_1_fu_518_p2 when (icmp_ln30_reg_715_pp0_iter3_reg(0) = '1') else 
        y_fu_126;
    select_ln29_fu_278_p3 <= 
        ap_const_lv9_0 when (icmp_ln30_fu_262_p2(0) = '1') else 
        x_fu_122;
    tmp_1_fu_540_p4 <= y_fu_126(30 downto 1);
    tmp_2_fu_333_p4 <= select_ln29_fu_278_p3(8 downto 1);
    tmp_fu_524_p4 <= add_ln29_1_fu_518_p2(30 downto 1);
    val_V_1_fu_300_p1 <= in_stream_TDATA(8 - 1 downto 0);
    valid_fu_595_p2 <= (select_ln29_1_fu_556_p3 and icmp_ln60_reg_758_pp0_iter3_reg);
    zext_ln30_1_fu_258_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(x_fu_122),32));
    zext_ln30_fu_286_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln29_fu_278_p3),64));
end behav;
