// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="morphology_morphology,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.761000,HLS_SYN_LAT=76804,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=285,HLS_SYN_LUT=585,HLS_VERSION=2022_1}" *)

module morphology (
        ap_clk,
        ap_rst_n,
        in_stream_TDATA,
        in_stream_TVALID,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TLAST,
        out_stream_TDATA,
        out_stream_TVALID,
        out_stream_TREADY,
        out_stream_TKEEP,
        out_stream_TSTRB,
        out_stream_TLAST,
        s_axi_CTRL_AWVALID,
        s_axi_CTRL_AWREADY,
        s_axi_CTRL_AWADDR,
        s_axi_CTRL_WVALID,
        s_axi_CTRL_WREADY,
        s_axi_CTRL_WDATA,
        s_axi_CTRL_WSTRB,
        s_axi_CTRL_ARVALID,
        s_axi_CTRL_ARREADY,
        s_axi_CTRL_ARADDR,
        s_axi_CTRL_RVALID,
        s_axi_CTRL_RREADY,
        s_axi_CTRL_RDATA,
        s_axi_CTRL_RRESP,
        s_axi_CTRL_BVALID,
        s_axi_CTRL_BREADY,
        s_axi_CTRL_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state6 = 3'd4;
parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [31:0] in_stream_TDATA;
input   in_stream_TVALID;
output   in_stream_TREADY;
input  [3:0] in_stream_TKEEP;
input  [3:0] in_stream_TSTRB;
input  [0:0] in_stream_TLAST;
output  [31:0] out_stream_TDATA;
output   out_stream_TVALID;
input   out_stream_TREADY;
output  [3:0] out_stream_TKEEP;
output  [3:0] out_stream_TSTRB;
output  [0:0] out_stream_TLAST;
input   s_axi_CTRL_AWVALID;
output   s_axi_CTRL_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_AWADDR;
input   s_axi_CTRL_WVALID;
output   s_axi_CTRL_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_CTRL_WSTRB;
input   s_axi_CTRL_ARVALID;
output   s_axi_CTRL_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_ARADDR;
output   s_axi_CTRL_RVALID;
input   s_axi_CTRL_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_RDATA;
output  [1:0] s_axi_CTRL_RRESP;
output   s_axi_CTRL_BVALID;
input   s_axi_CTRL_BREADY;
output  [1:0] s_axi_CTRL_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] width;
wire   [31:0] height;
reg    in_stream_TDATA_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
wire   [0:0] icmp_ln32_fu_272_p2;
reg    out_stream_TDATA_blk_n;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
wire   [0:0] and_ln63_fu_245_p2;
reg   [0:0] and_ln63_reg_643;
reg   [0:0] icmp_ln32_reg_648;
reg    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_state4_pp0_stage0_iter2;
reg    ap_block_state5_pp0_stage0_iter3;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln33_fu_290_p2;
reg   [0:0] icmp_ln33_reg_652;
reg   [0:0] icmp_ln33_reg_652_pp0_iter1_reg;
reg   [0:0] tmp_last_V_reg_658;
reg   [0:0] tmp_last_V_reg_658_pp0_iter1_reg;
reg   [8:0] line_buffer_0_V_addr_reg_663;
wire   [0:0] icmp_ln1069_6_fu_323_p2;
reg   [0:0] icmp_ln1069_6_reg_674;
wire   [0:0] icmp_ln1069_7_fu_329_p2;
reg   [0:0] icmp_ln1069_7_reg_679;
wire   [0:0] icmp_ln1069_8_fu_335_p2;
reg   [0:0] icmp_ln1069_8_reg_684;
wire   [0:0] icmp_ln63_fu_351_p2;
reg   [0:0] icmp_ln63_reg_689;
reg   [0:0] icmp_ln63_reg_689_pp0_iter1_reg;
wire   [0:0] eroded_V_fu_476_p2;
reg   [0:0] eroded_V_reg_694;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_flush_enable;
reg    ap_enable_reg_pp0_iter1;
reg    ap_condition_pp0_exit_iter1_state3;
reg    line_buffer_0_V_ce0;
reg    line_buffer_0_V_we0;
wire   [8:0] line_buffer_0_V_address1;
reg    line_buffer_0_V_ce1;
wire   [7:0] line_buffer_0_V_q1;
wire   [8:0] line_buffer_1_V_address0;
reg    line_buffer_1_V_ce0;
reg    line_buffer_1_V_we0;
wire   [7:0] line_buffer_1_V_q0;
wire   [63:0] zext_ln33_fu_304_p1;
reg   [7:0] p_0_0_076307_fu_118;
reg   [7:0] p_0_0_074309_fu_122;
reg   [7:0] p_0_0_072311_fu_126;
reg   [8:0] x_fu_130;
wire   [8:0] add_ln33_fu_357_p2;
reg   [7:0] y_fu_134;
wire   [7:0] select_ln32_2_fu_550_p3;
reg   [16:0] indvar_flatten_fu_138;
wire   [16:0] add_ln32_fu_278_p2;
reg   [7:0] p_0_0_075308_fu_142;
reg   [7:0] p_0_0_073310_fu_146;
reg   [7:0] value_V_fu_150;
wire   [7:0] value_V_1_fu_318_p1;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] icmp_ln30_fu_233_p2;
wire   [0:0] icmp_ln30_1_fu_239_p2;
wire   [8:0] select_ln32_fu_296_p3;
wire   [7:0] tmp_2_fu_341_p4;
wire   [0:0] icmp_ln1069_5_fu_425_p2;
wire   [0:0] or_ln57_1_fu_435_p2;
wire   [0:0] or_ln57_fu_431_p2;
wire   [0:0] icmp_ln1069_1_fu_401_p2;
wire   [0:0] icmp_ln1069_2_fu_407_p2;
wire   [0:0] icmp_ln1069_4_fu_419_p2;
wire   [0:0] icmp_ln1069_fu_395_p2;
wire   [0:0] or_ln57_4_fu_452_p2;
wire   [0:0] icmp_ln1069_3_fu_413_p2;
wire   [0:0] or_ln57_5_fu_458_p2;
wire   [0:0] or_ln57_3_fu_446_p2;
wire   [0:0] or_ln57_6_fu_464_p2;
wire   [0:0] or_ln57_2_fu_440_p2;
wire   [0:0] or_ln57_7_fu_470_p2;
wire   [7:0] add_ln32_1_fu_505_p2;
wire   [6:0] tmp_fu_511_p4;
wire   [6:0] tmp_1_fu_527_p4;
wire   [0:0] icmp_fu_521_p2;
wire   [0:0] icmp19_fu_537_p2;
wire   [0:0] select_ln32_1_fu_543_p3;
wire   [0:0] and_ln63_1_fu_557_p2;
wire   [0:0] and_ln63_2_fu_562_p2;
wire   [0:0] output_data_V_fu_567_p2;
wire    ap_CS_fsm_state6;
wire    regslice_both_out_stream_V_data_V_U_apdone_blk;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state6_blk;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    regslice_both_in_stream_V_data_V_U_apdone_blk;
wire   [31:0] in_stream_TDATA_int_regslice;
wire    in_stream_TVALID_int_regslice;
reg    in_stream_TREADY_int_regslice;
wire    regslice_both_in_stream_V_data_V_U_ack_in;
wire    regslice_both_in_stream_V_keep_V_U_apdone_blk;
wire   [3:0] in_stream_TKEEP_int_regslice;
wire    regslice_both_in_stream_V_keep_V_U_vld_out;
wire    regslice_both_in_stream_V_keep_V_U_ack_in;
wire    regslice_both_in_stream_V_strb_V_U_apdone_blk;
wire   [3:0] in_stream_TSTRB_int_regslice;
wire    regslice_both_in_stream_V_strb_V_U_vld_out;
wire    regslice_both_in_stream_V_strb_V_U_ack_in;
wire    regslice_both_in_stream_V_last_V_U_apdone_blk;
wire   [0:0] in_stream_TLAST_int_regslice;
wire    regslice_both_in_stream_V_last_V_U_vld_out;
wire    regslice_both_in_stream_V_last_V_U_ack_in;
wire   [31:0] out_stream_TDATA_int_regslice;
reg    out_stream_TVALID_int_regslice;
wire    out_stream_TREADY_int_regslice;
wire    regslice_both_out_stream_V_data_V_U_vld_out;
wire    regslice_both_out_stream_V_keep_V_U_apdone_blk;
wire    regslice_both_out_stream_V_keep_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_keep_V_U_vld_out;
wire    regslice_both_out_stream_V_strb_V_U_apdone_blk;
wire    regslice_both_out_stream_V_strb_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_strb_V_U_vld_out;
wire    regslice_both_out_stream_V_last_V_U_apdone_blk;
wire    regslice_both_out_stream_V_last_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

morphology_line_buffer_0_V_RAM_T2P_BRAM_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 320 ),
    .AddressWidth( 9 ))
line_buffer_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(line_buffer_0_V_addr_reg_663),
    .ce0(line_buffer_0_V_ce0),
    .we0(line_buffer_0_V_we0),
    .d0(line_buffer_1_V_q0),
    .address1(line_buffer_0_V_address1),
    .ce1(line_buffer_0_V_ce1),
    .q1(line_buffer_0_V_q1)
);

morphology_line_buffer_1_V_RAM_T2P_BRAM_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 320 ),
    .AddressWidth( 9 ))
line_buffer_1_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(line_buffer_1_V_address0),
    .ce0(line_buffer_1_V_ce0),
    .we0(line_buffer_1_V_we0),
    .d0(value_V_1_fu_318_p1),
    .q0(line_buffer_1_V_q0)
);

morphology_CTRL_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
CTRL_s_axi_U(
    .AWVALID(s_axi_CTRL_AWVALID),
    .AWREADY(s_axi_CTRL_AWREADY),
    .AWADDR(s_axi_CTRL_AWADDR),
    .WVALID(s_axi_CTRL_WVALID),
    .WREADY(s_axi_CTRL_WREADY),
    .WDATA(s_axi_CTRL_WDATA),
    .WSTRB(s_axi_CTRL_WSTRB),
    .ARVALID(s_axi_CTRL_ARVALID),
    .ARREADY(s_axi_CTRL_ARREADY),
    .ARADDR(s_axi_CTRL_ARADDR),
    .RVALID(s_axi_CTRL_RVALID),
    .RREADY(s_axi_CTRL_RREADY),
    .RDATA(s_axi_CTRL_RDATA),
    .RRESP(s_axi_CTRL_RRESP),
    .BVALID(s_axi_CTRL_BVALID),
    .BREADY(s_axi_CTRL_BREADY),
    .BRESP(s_axi_CTRL_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .width(width),
    .height(height),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

morphology_regslice_both #(
    .DataWidth( 32 ))
regslice_both_in_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TDATA),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_data_V_U_ack_in),
    .data_out(in_stream_TDATA_int_regslice),
    .vld_out(in_stream_TVALID_int_regslice),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_data_V_U_apdone_blk)
);

morphology_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TKEEP),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_keep_V_U_ack_in),
    .data_out(in_stream_TKEEP_int_regslice),
    .vld_out(regslice_both_in_stream_V_keep_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_keep_V_U_apdone_blk)
);

morphology_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TSTRB),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_strb_V_U_ack_in),
    .data_out(in_stream_TSTRB_int_regslice),
    .vld_out(regslice_both_in_stream_V_strb_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_strb_V_U_apdone_blk)
);

morphology_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TLAST),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_last_V_U_ack_in),
    .data_out(in_stream_TLAST_int_regslice),
    .vld_out(regslice_both_in_stream_V_last_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_last_V_U_apdone_blk)
);

morphology_regslice_both #(
    .DataWidth( 32 ))
regslice_both_out_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_stream_TDATA_int_regslice),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(out_stream_TREADY_int_regslice),
    .data_out(out_stream_TDATA),
    .vld_out(regslice_both_out_stream_V_data_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_data_V_U_apdone_blk)
);

morphology_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd15),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_keep_V_U_ack_in_dummy),
    .data_out(out_stream_TKEEP),
    .vld_out(regslice_both_out_stream_V_keep_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_keep_V_U_apdone_blk)
);

morphology_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd15),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_strb_V_U_ack_in_dummy),
    .data_out(out_stream_TSTRB),
    .vld_out(regslice_both_out_stream_V_strb_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_strb_V_U_apdone_blk)
);

morphology_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(tmp_last_V_reg_658_pp0_iter1_reg),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_last_V_U_ack_in_dummy),
    .data_out(out_stream_TLAST),
    .vld_out(regslice_both_out_stream_V_last_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp0_flush_enable)) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter1_state3)) begin
                ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter0;
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        indvar_flatten_fu_138 <= 17'd0;
    end else if (((icmp_ln32_fu_272_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten_fu_138 <= add_ln32_fu_278_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        x_fu_130 <= 9'd0;
    end else if (((icmp_ln32_fu_272_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_fu_130 <= add_ln33_fu_357_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        y_fu_134 <= 8'd0;
    end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        y_fu_134 <= select_ln32_2_fu_550_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        and_ln63_reg_643 <= and_ln63_fu_245_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln32_reg_648 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        eroded_V_reg_694 <= eroded_V_fu_476_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln32_fu_272_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln1069_6_reg_674 <= icmp_ln1069_6_fu_323_p2;
        icmp_ln1069_7_reg_679 <= icmp_ln1069_7_fu_329_p2;
        icmp_ln1069_8_reg_684 <= icmp_ln1069_8_fu_335_p2;
        icmp_ln33_reg_652 <= icmp_ln33_fu_290_p2;
        icmp_ln63_reg_689 <= icmp_ln63_fu_351_p2;
        line_buffer_0_V_addr_reg_663 <= zext_ln33_fu_304_p1;
        tmp_last_V_reg_658 <= in_stream_TLAST_int_regslice;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln32_reg_648 <= icmp_ln32_fu_272_p2;
        icmp_ln33_reg_652_pp0_iter1_reg <= icmp_ln33_reg_652;
        icmp_ln63_reg_689_pp0_iter1_reg <= icmp_ln63_reg_689;
        tmp_last_V_reg_658_pp0_iter1_reg <= tmp_last_V_reg_658;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln32_fu_272_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_0_072311_fu_126 <= value_V_fu_150;
        value_V_fu_150 <= value_V_1_fu_318_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln32_reg_648 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        p_0_0_073310_fu_146 <= line_buffer_1_V_q0;
        p_0_0_074309_fu_122 <= p_0_0_073310_fu_146;
        p_0_0_075308_fu_142 <= line_buffer_0_V_q1;
        p_0_0_076307_fu_118 <= p_0_0_075308_fu_142;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        ap_condition_pp0_exit_iter1_state3 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter1_state3 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln32_fu_272_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_pp0_flush_enable = 1'b1;
    end else begin
        ap_condition_pp0_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln32_fu_272_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_stream_TDATA_blk_n = in_stream_TVALID_int_regslice;
    end else begin
        in_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln32_fu_272_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_stream_TREADY_int_regslice = 1'b1;
    end else begin
        in_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        line_buffer_0_V_ce0 = 1'b1;
    end else begin
        line_buffer_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_0_V_ce1 = 1'b1;
    end else begin
        line_buffer_0_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln32_reg_648 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        line_buffer_0_V_we0 = 1'b1;
    end else begin
        line_buffer_0_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln32_fu_272_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_1_V_ce0 = 1'b1;
    end else begin
        line_buffer_1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln32_fu_272_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_1_V_we0 = 1'b1;
    end else begin
        line_buffer_1_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0)))) begin
        out_stream_TDATA_blk_n = out_stream_TREADY_int_regslice;
    end else begin
        out_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        out_stream_TVALID_int_regslice = 1'b1;
    end else begin
        out_stream_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter2 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1)) & ~((ap_enable_reg_pp0_iter3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone)) | ((ap_enable_reg_pp0_iter2 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln32_1_fu_505_p2 = (y_fu_134 + 8'd1);

assign add_ln32_fu_278_p2 = (indvar_flatten_fu_138 + 17'd1);

assign add_ln33_fu_357_p2 = (select_ln32_fu_296_p3 + 9'd1);

assign and_ln63_1_fu_557_p2 = (select_ln32_1_fu_543_p3 & icmp_ln63_reg_689_pp0_iter1_reg);

assign and_ln63_2_fu_562_p2 = (and_ln63_reg_643 & and_ln63_1_fu_557_p2);

assign and_ln63_fu_245_p2 = (icmp_ln30_fu_233_p2 & icmp_ln30_1_fu_239_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter3 == 1'b1) & (out_stream_TREADY_int_regslice == 1'b0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (out_stream_TREADY_int_regslice == 1'b0)) | ((icmp_ln32_fu_272_p2 == 1'd0) & (in_stream_TVALID_int_regslice == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter3 == 1'b1) & (out_stream_TREADY_int_regslice == 1'b0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (out_stream_TREADY_int_regslice == 1'b0)) | ((icmp_ln32_fu_272_p2 == 1'd0) & (in_stream_TVALID_int_regslice == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter3 == 1'b1) & (out_stream_TREADY_int_regslice == 1'b0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (out_stream_TREADY_int_regslice == 1'b0)) | ((icmp_ln32_fu_272_p2 == 1'd0) & (in_stream_TVALID_int_regslice == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter0 = ((icmp_ln32_fu_272_p2 == 1'd0) & (in_stream_TVALID_int_regslice == 1'b0));
end

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_pp0_stage0_iter2 = (out_stream_TREADY_int_regslice == 1'b0);
end

always @ (*) begin
    ap_block_state5_pp0_stage0_iter3 = (out_stream_TREADY_int_regslice == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign eroded_V_fu_476_p2 = (or_ln57_7_fu_470_p2 ^ 1'd1);

assign icmp19_fu_537_p2 = ((tmp_1_fu_527_p4 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_fu_521_p2 = ((tmp_fu_511_p4 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln1069_1_fu_401_p2 = ((p_0_0_075308_fu_142 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln1069_2_fu_407_p2 = ((line_buffer_0_V_q1 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln1069_3_fu_413_p2 = ((p_0_0_074309_fu_122 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln1069_4_fu_419_p2 = ((p_0_0_073310_fu_146 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln1069_5_fu_425_p2 = ((line_buffer_1_V_q0 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln1069_6_fu_323_p2 = ((p_0_0_072311_fu_126 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln1069_7_fu_329_p2 = ((value_V_fu_150 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln1069_8_fu_335_p2 = ((value_V_1_fu_318_p1 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln1069_fu_395_p2 = ((p_0_0_076307_fu_118 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln30_1_fu_239_p2 = ((height == 32'd240) ? 1'b1 : 1'b0);

assign icmp_ln30_fu_233_p2 = ((width == 32'd320) ? 1'b1 : 1'b0);

assign icmp_ln32_fu_272_p2 = ((indvar_flatten_fu_138 == 17'd76800) ? 1'b1 : 1'b0);

assign icmp_ln33_fu_290_p2 = ((x_fu_130 == 9'd320) ? 1'b1 : 1'b0);

assign icmp_ln63_fu_351_p2 = ((tmp_2_fu_341_p4 != 8'd0) ? 1'b1 : 1'b0);

assign in_stream_TREADY = regslice_both_in_stream_V_data_V_U_ack_in;

assign line_buffer_0_V_address1 = zext_ln33_fu_304_p1;

assign line_buffer_1_V_address0 = zext_ln33_fu_304_p1;

assign or_ln57_1_fu_435_p2 = (icmp_ln1069_6_reg_674 | icmp_ln1069_5_fu_425_p2);

assign or_ln57_2_fu_440_p2 = (or_ln57_fu_431_p2 | or_ln57_1_fu_435_p2);

assign or_ln57_3_fu_446_p2 = (icmp_ln1069_2_fu_407_p2 | icmp_ln1069_1_fu_401_p2);

assign or_ln57_4_fu_452_p2 = (icmp_ln1069_fu_395_p2 | icmp_ln1069_4_fu_419_p2);

assign or_ln57_5_fu_458_p2 = (or_ln57_4_fu_452_p2 | icmp_ln1069_3_fu_413_p2);

assign or_ln57_6_fu_464_p2 = (or_ln57_5_fu_458_p2 | or_ln57_3_fu_446_p2);

assign or_ln57_7_fu_470_p2 = (or_ln57_6_fu_464_p2 | or_ln57_2_fu_440_p2);

assign or_ln57_fu_431_p2 = (icmp_ln1069_8_reg_684 | icmp_ln1069_7_reg_679);

assign out_stream_TDATA_int_regslice = ((output_data_V_fu_567_p2[0:0] == 1'b1) ? 32'd255 : 32'd0);

assign out_stream_TVALID = regslice_both_out_stream_V_data_V_U_vld_out;

assign output_data_V_fu_567_p2 = (eroded_V_reg_694 & and_ln63_2_fu_562_p2);

assign select_ln32_1_fu_543_p3 = ((icmp_ln33_reg_652_pp0_iter1_reg[0:0] == 1'b1) ? icmp_fu_521_p2 : icmp19_fu_537_p2);

assign select_ln32_2_fu_550_p3 = ((icmp_ln33_reg_652_pp0_iter1_reg[0:0] == 1'b1) ? add_ln32_1_fu_505_p2 : y_fu_134);

assign select_ln32_fu_296_p3 = ((icmp_ln33_fu_290_p2[0:0] == 1'b1) ? 9'd0 : x_fu_130);

assign tmp_1_fu_527_p4 = {{y_fu_134[7:1]}};

assign tmp_2_fu_341_p4 = {{select_ln32_fu_296_p3[8:1]}};

assign tmp_fu_511_p4 = {{add_ln32_1_fu_505_p2[7:1]}};

assign value_V_1_fu_318_p1 = in_stream_TDATA_int_regslice[7:0];

assign zext_ln33_fu_304_p1 = select_ln32_fu_296_p3;


reg find_kernel_block = 0;
// synthesis translate_off
`include "morphology_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //morphology

