// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="morphology_morphology,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.031000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=958,HLS_SYN_LUT=936,HLS_VERSION=2022_1}" *)

module morphology (
        ap_clk,
        ap_rst_n,
        in_stream_TDATA,
        in_stream_TVALID,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TLAST,
        out_stream_TDATA,
        out_stream_TVALID,
        out_stream_TREADY,
        out_stream_TKEEP,
        out_stream_TSTRB,
        out_stream_TLAST,
        s_axi_CTRL_AWVALID,
        s_axi_CTRL_AWREADY,
        s_axi_CTRL_AWADDR,
        s_axi_CTRL_WVALID,
        s_axi_CTRL_WREADY,
        s_axi_CTRL_WDATA,
        s_axi_CTRL_WSTRB,
        s_axi_CTRL_ARVALID,
        s_axi_CTRL_ARREADY,
        s_axi_CTRL_ARADDR,
        s_axi_CTRL_RVALID,
        s_axi_CTRL_RREADY,
        s_axi_CTRL_RDATA,
        s_axi_CTRL_RRESP,
        s_axi_CTRL_BVALID,
        s_axi_CTRL_BREADY,
        s_axi_CTRL_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;
parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [31:0] in_stream_TDATA;
input   in_stream_TVALID;
output   in_stream_TREADY;
input  [3:0] in_stream_TKEEP;
input  [3:0] in_stream_TSTRB;
input  [0:0] in_stream_TLAST;
output  [31:0] out_stream_TDATA;
output   out_stream_TVALID;
input   out_stream_TREADY;
output  [3:0] out_stream_TKEEP;
output  [3:0] out_stream_TSTRB;
output  [0:0] out_stream_TLAST;
input   s_axi_CTRL_AWVALID;
output   s_axi_CTRL_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_AWADDR;
input   s_axi_CTRL_WVALID;
output   s_axi_CTRL_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_CTRL_WSTRB;
input   s_axi_CTRL_ARVALID;
output   s_axi_CTRL_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_ARADDR;
output   s_axi_CTRL_RVALID;
input   s_axi_CTRL_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_RDATA;
output  [1:0] s_axi_CTRL_RRESP;
output   s_axi_CTRL_BVALID;
input   s_axi_CTRL_BREADY;
output  [1:0] s_axi_CTRL_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] width;
wire   [31:0] height;
reg   [31:0] height_read_reg_122;
reg   [31:0] width_read_reg_127;
wire    ap_CS_fsm_state2;
wire   [63:0] grp_fu_116_p2;
reg   [63:0] mul_ln9_reg_143;
wire    ap_CS_fsm_state3;
wire   [7:0] line_buf0_V_q1;
wire   [7:0] line_buf1_V_q0;
wire    grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_ap_start;
wire    grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_ap_done;
wire    grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_ap_idle;
wire    grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_ap_ready;
wire    grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_out_stream_TREADY;
wire    grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_in_stream_TREADY;
wire   [8:0] grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf0_V_address0;
wire    grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf0_V_ce0;
wire    grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf0_V_we0;
wire   [7:0] grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf0_V_d0;
wire   [8:0] grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf0_V_address1;
wire    grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf0_V_ce1;
wire   [8:0] grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf1_V_address0;
wire    grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf1_V_ce0;
wire    grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf1_V_we0;
wire   [7:0] grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf1_V_d0;
wire   [31:0] grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_out_stream_TDATA;
wire    grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_out_stream_TVALID;
wire   [3:0] grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_out_stream_TKEEP;
wire   [3:0] grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_out_stream_TSTRB;
wire   [0:0] grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_out_stream_TLAST;
reg    grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_ap_start_reg;
reg   [5:0] ap_NS_fsm;
wire    ap_NS_fsm_state4;
wire    ap_CS_fsm_state5;
wire   [31:0] grp_fu_116_p0;
wire   [31:0] grp_fu_116_p1;
wire    ap_CS_fsm_state6;
wire    regslice_both_out_stream_V_data_V_U_apdone_blk;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    regslice_both_in_stream_V_data_V_U_apdone_blk;
wire   [31:0] in_stream_TDATA_int_regslice;
wire    in_stream_TVALID_int_regslice;
reg    in_stream_TREADY_int_regslice;
wire    regslice_both_in_stream_V_data_V_U_ack_in;
wire    regslice_both_in_stream_V_keep_V_U_apdone_blk;
wire   [3:0] in_stream_TKEEP_int_regslice;
wire    regslice_both_in_stream_V_keep_V_U_vld_out;
wire    regslice_both_in_stream_V_keep_V_U_ack_in;
wire    regslice_both_in_stream_V_strb_V_U_apdone_blk;
wire   [3:0] in_stream_TSTRB_int_regslice;
wire    regslice_both_in_stream_V_strb_V_U_vld_out;
wire    regslice_both_in_stream_V_strb_V_U_ack_in;
wire    regslice_both_in_stream_V_last_V_U_apdone_blk;
wire   [0:0] in_stream_TLAST_int_regslice;
wire    regslice_both_in_stream_V_last_V_U_vld_out;
wire    regslice_both_in_stream_V_last_V_U_ack_in;
wire    out_stream_TVALID_int_regslice;
wire    out_stream_TREADY_int_regslice;
wire    regslice_both_out_stream_V_data_V_U_vld_out;
wire    regslice_both_out_stream_V_keep_V_U_apdone_blk;
wire    regslice_both_out_stream_V_keep_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_keep_V_U_vld_out;
wire    regslice_both_out_stream_V_strb_V_U_apdone_blk;
wire    regslice_both_out_stream_V_strb_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_strb_V_U_vld_out;
wire    regslice_both_out_stream_V_last_V_U_apdone_blk;
wire    regslice_both_out_stream_V_last_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_last_V_U_vld_out;
wire   [63:0] grp_fu_116_p00;
wire   [63:0] grp_fu_116_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_ap_start_reg = 1'b0;
end

morphology_line_buf0_V_RAM_T2P_BRAM_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 320 ),
    .AddressWidth( 9 ))
line_buf0_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf0_V_address0),
    .ce0(grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf0_V_ce0),
    .we0(grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf0_V_we0),
    .d0(grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf0_V_d0),
    .address1(grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf0_V_address1),
    .ce1(grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf0_V_ce1),
    .q1(line_buf0_V_q1)
);

morphology_line_buf1_V_RAM_T2P_BRAM_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 320 ),
    .AddressWidth( 9 ))
line_buf1_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf1_V_address0),
    .ce0(grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf1_V_ce0),
    .we0(grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf1_V_we0),
    .d0(grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf1_V_d0),
    .q0(line_buf1_V_q0)
);

morphology_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2 grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_ap_start),
    .ap_done(grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_ap_done),
    .ap_idle(grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_ap_idle),
    .ap_ready(grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_ap_ready),
    .in_stream_TVALID(in_stream_TVALID_int_regslice),
    .out_stream_TREADY(grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_out_stream_TREADY),
    .width(width_read_reg_127),
    .mul_ln9(mul_ln9_reg_143),
    .in_stream_TDATA(in_stream_TDATA_int_regslice),
    .in_stream_TREADY(grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_in_stream_TREADY),
    .in_stream_TKEEP(in_stream_TKEEP_int_regslice),
    .in_stream_TSTRB(in_stream_TSTRB_int_regslice),
    .in_stream_TLAST(in_stream_TLAST_int_regslice),
    .line_buf0_V_address0(grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf0_V_address0),
    .line_buf0_V_ce0(grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf0_V_ce0),
    .line_buf0_V_we0(grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf0_V_we0),
    .line_buf0_V_d0(grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf0_V_d0),
    .line_buf0_V_address1(grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf0_V_address1),
    .line_buf0_V_ce1(grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf0_V_ce1),
    .line_buf0_V_q1(line_buf0_V_q1),
    .line_buf1_V_address0(grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf1_V_address0),
    .line_buf1_V_ce0(grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf1_V_ce0),
    .line_buf1_V_we0(grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf1_V_we0),
    .line_buf1_V_d0(grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_line_buf1_V_d0),
    .line_buf1_V_q0(line_buf1_V_q0),
    .out_stream_TDATA(grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_out_stream_TDATA),
    .out_stream_TVALID(grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_out_stream_TVALID),
    .out_stream_TKEEP(grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_out_stream_TKEEP),
    .out_stream_TSTRB(grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_out_stream_TSTRB),
    .out_stream_TLAST(grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_out_stream_TLAST)
);

morphology_CTRL_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
CTRL_s_axi_U(
    .AWVALID(s_axi_CTRL_AWVALID),
    .AWREADY(s_axi_CTRL_AWREADY),
    .AWADDR(s_axi_CTRL_AWADDR),
    .WVALID(s_axi_CTRL_WVALID),
    .WREADY(s_axi_CTRL_WREADY),
    .WDATA(s_axi_CTRL_WDATA),
    .WSTRB(s_axi_CTRL_WSTRB),
    .ARVALID(s_axi_CTRL_ARVALID),
    .ARREADY(s_axi_CTRL_ARREADY),
    .ARADDR(s_axi_CTRL_ARADDR),
    .RVALID(s_axi_CTRL_RVALID),
    .RREADY(s_axi_CTRL_RREADY),
    .RDATA(s_axi_CTRL_RDATA),
    .RRESP(s_axi_CTRL_RRESP),
    .BVALID(s_axi_CTRL_BVALID),
    .BREADY(s_axi_CTRL_BREADY),
    .BRESP(s_axi_CTRL_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .width(width),
    .height(height),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

morphology_mul_32ns_32ns_64_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_2_1_U13(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_116_p0),
    .din1(grp_fu_116_p1),
    .ce(1'b1),
    .dout(grp_fu_116_p2)
);

morphology_regslice_both #(
    .DataWidth( 32 ))
regslice_both_in_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TDATA),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_data_V_U_ack_in),
    .data_out(in_stream_TDATA_int_regslice),
    .vld_out(in_stream_TVALID_int_regslice),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_data_V_U_apdone_blk)
);

morphology_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TKEEP),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_keep_V_U_ack_in),
    .data_out(in_stream_TKEEP_int_regslice),
    .vld_out(regslice_both_in_stream_V_keep_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_keep_V_U_apdone_blk)
);

morphology_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TSTRB),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_strb_V_U_ack_in),
    .data_out(in_stream_TSTRB_int_regslice),
    .vld_out(regslice_both_in_stream_V_strb_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_strb_V_U_apdone_blk)
);

morphology_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TLAST),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_last_V_U_ack_in),
    .data_out(in_stream_TLAST_int_regslice),
    .vld_out(regslice_both_in_stream_V_last_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_last_V_U_apdone_blk)
);

morphology_regslice_both #(
    .DataWidth( 32 ))
regslice_both_out_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_out_stream_TDATA),
    .vld_in(grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_out_stream_TVALID),
    .ack_in(out_stream_TREADY_int_regslice),
    .data_out(out_stream_TDATA),
    .vld_out(regslice_both_out_stream_V_data_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_data_V_U_apdone_blk)
);

morphology_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_out_stream_TKEEP),
    .vld_in(grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_out_stream_TVALID),
    .ack_in(regslice_both_out_stream_V_keep_V_U_ack_in_dummy),
    .data_out(out_stream_TKEEP),
    .vld_out(regslice_both_out_stream_V_keep_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_keep_V_U_apdone_blk)
);

morphology_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_out_stream_TSTRB),
    .vld_in(grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_out_stream_TVALID),
    .ack_in(regslice_both_out_stream_V_strb_V_U_ack_in_dummy),
    .data_out(out_stream_TSTRB),
    .vld_out(regslice_both_out_stream_V_strb_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_strb_V_U_apdone_blk)
);

morphology_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_out_stream_TLAST),
    .vld_in(grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_out_stream_TVALID),
    .ack_in(regslice_both_out_stream_V_last_V_U_ack_in_dummy),
    .data_out(out_stream_TLAST),
    .vld_out(regslice_both_out_stream_V_last_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state3) & (1'b1 == ap_NS_fsm_state4))) begin
            grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_ap_start_reg <= 1'b1;
        end else if ((grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_ap_ready == 1'b1)) begin
            grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        height_read_reg_122 <= height;
        width_read_reg_127 <= width;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        mul_ln9_reg_143 <= grp_fu_116_p2;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        in_stream_TREADY_int_regslice = grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_in_stream_TREADY;
    end else begin
        in_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_NS_fsm_state4 = ap_NS_fsm[32'd3];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_fu_116_p0 = grp_fu_116_p00;

assign grp_fu_116_p00 = height_read_reg_122;

assign grp_fu_116_p1 = grp_fu_116_p10;

assign grp_fu_116_p10 = width_read_reg_127;

assign grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_ap_start = grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_ap_start_reg;

assign grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_out_stream_TREADY = (out_stream_TREADY_int_regslice & ap_CS_fsm_state5);

assign in_stream_TREADY = regslice_both_in_stream_V_data_V_U_ack_in;

assign out_stream_TVALID = regslice_both_out_stream_V_data_V_U_vld_out;

assign out_stream_TVALID_int_regslice = grp_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2_fu_86_out_stream_TVALID;


reg find_kernel_block = 0;
// synthesis translate_off
`include "morphology_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //morphology

