// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module morphology_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_stream_TVALID,
        out_stream_TREADY,
        width,
        mul_ln9,
        in_stream_TDATA,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TLAST,
        line_buf0_V_address0,
        line_buf0_V_ce0,
        line_buf0_V_we0,
        line_buf0_V_d0,
        line_buf0_V_address1,
        line_buf0_V_ce1,
        line_buf0_V_q1,
        line_buf1_V_address0,
        line_buf1_V_ce0,
        line_buf1_V_we0,
        line_buf1_V_d0,
        line_buf1_V_q0,
        out_stream_TDATA,
        out_stream_TVALID,
        out_stream_TKEEP,
        out_stream_TSTRB,
        out_stream_TLAST
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in_stream_TVALID;
input   out_stream_TREADY;
input  [31:0] width;
input  [63:0] mul_ln9;
input  [31:0] in_stream_TDATA;
output   in_stream_TREADY;
input  [3:0] in_stream_TKEEP;
input  [3:0] in_stream_TSTRB;
input  [0:0] in_stream_TLAST;
output  [8:0] line_buf0_V_address0;
output   line_buf0_V_ce0;
output   line_buf0_V_we0;
output  [7:0] line_buf0_V_d0;
output  [8:0] line_buf0_V_address1;
output   line_buf0_V_ce1;
input  [7:0] line_buf0_V_q1;
output  [8:0] line_buf1_V_address0;
output   line_buf1_V_ce0;
output   line_buf1_V_we0;
output  [7:0] line_buf1_V_d0;
input  [7:0] line_buf1_V_q0;
output  [31:0] out_stream_TDATA;
output   out_stream_TVALID;
output  [3:0] out_stream_TKEEP;
output  [3:0] out_stream_TSTRB;
output  [0:0] out_stream_TLAST;

reg ap_idle;
reg in_stream_TREADY;
reg line_buf0_V_ce0;
reg line_buf0_V_we0;
reg line_buf0_V_ce1;
reg line_buf1_V_ce0;
reg line_buf1_V_we0;
reg out_stream_TVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln29_fu_267_p2;
reg    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
reg    ap_block_state5_pp0_stage0_iter4;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    in_stream_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    out_stream_TDATA_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln30_fu_262_p2;
reg   [0:0] icmp_ln30_reg_715;
reg   [0:0] icmp_ln30_reg_715_pp0_iter2_reg;
reg   [0:0] icmp_ln30_reg_715_pp0_iter3_reg;
reg   [0:0] icmp_ln29_reg_721;
reg   [0:0] icmp_ln29_reg_721_pp0_iter2_reg;
reg   [0:0] tmp_last_V_reg_725;
reg   [0:0] tmp_last_V_reg_725_pp0_iter2_reg;
reg   [0:0] tmp_last_V_reg_725_pp0_iter3_reg;
wire   [7:0] val_V_1_fu_300_p1;
reg   [7:0] val_V_1_reg_730;
reg   [8:0] line_buf0_V_addr_reg_737;
reg   [8:0] line_buf0_V_addr_reg_737_pp0_iter2_reg;
wire   [0:0] addr_cmp22_fu_308_p2;
reg   [0:0] addr_cmp22_reg_743;
reg   [0:0] addr_cmp22_reg_743_pp0_iter2_reg;
wire   [0:0] addr_cmp_fu_317_p2;
reg   [0:0] addr_cmp_reg_753;
wire   [0:0] icmp_ln60_fu_343_p2;
reg   [0:0] icmp_ln60_reg_758;
reg   [0:0] icmp_ln60_reg_758_pp0_iter2_reg;
reg   [0:0] icmp_ln60_reg_758_pp0_iter3_reg;
wire   [7:0] reuse_select_fu_374_p3;
reg   [7:0] reuse_select_reg_763;
wire   [0:0] icmp_ln1069_6_fu_385_p2;
reg   [0:0] icmp_ln1069_6_reg_771;
reg   [0:0] icmp_ln1069_6_reg_771_pp0_iter3_reg;
wire   [0:0] icmp_ln1069_7_fu_391_p2;
reg   [0:0] icmp_ln1069_7_reg_776;
reg   [0:0] icmp_ln1069_7_reg_776_pp0_iter3_reg;
wire   [0:0] icmp_ln1069_8_fu_397_p2;
reg   [0:0] icmp_ln1069_8_reg_781;
reg   [0:0] icmp_ln1069_8_reg_781_pp0_iter3_reg;
wire   [0:0] icmp_ln1069_5_fu_467_p2;
reg   [0:0] icmp_ln1069_5_reg_786;
wire   [0:0] or_ln54_6_fu_490_p2;
reg   [0:0] or_ln54_6_reg_791;
reg    ap_condition_exit_pp0_iter3_stage0;
wire   [63:0] zext_ln30_fu_286_p1;
reg   [63:0] reuse_addr_reg19_fu_94;
wire    ap_loop_init;
reg   [7:0] reuse_reg18_fu_98;
reg   [63:0] reuse_addr_reg_fu_102;
reg   [7:0] reuse_reg_fu_106;
reg   [7:0] p_0_0_076307_fu_110;
reg   [7:0] p_0_0_074309_fu_114;
reg   [7:0] p_0_0_072311_fu_118;
reg   [8:0] x_fu_122;
wire   [8:0] add_ln30_fu_349_p2;
reg   [30:0] y_fu_126;
wire   [30:0] select_ln29_2_fu_563_p3;
reg   [63:0] indvar_flatten_fu_130;
wire   [63:0] add_ln29_fu_272_p2;
reg   [7:0] p_0_0_075308_fu_134;
wire   [7:0] reuse_select23_fu_426_p3;
reg   [7:0] p_0_0_073310_fu_138;
reg   [7:0] val_V_fu_142;
reg    ap_block_pp0_stage0_01001;
wire   [31:0] zext_ln30_1_fu_258_p1;
wire   [8:0] select_ln29_fu_278_p3;
wire   [7:0] tmp_2_fu_333_p4;
wire   [0:0] icmp_ln1069_1_fu_443_p2;
wire   [0:0] icmp_ln1069_2_fu_449_p2;
wire   [0:0] icmp_ln1069_4_fu_461_p2;
wire   [0:0] icmp_ln1069_fu_437_p2;
wire   [0:0] or_ln54_4_fu_478_p2;
wire   [0:0] icmp_ln1069_3_fu_455_p2;
wire   [0:0] or_ln54_5_fu_484_p2;
wire   [0:0] or_ln54_3_fu_472_p2;
wire   [30:0] add_ln29_1_fu_518_p2;
wire   [29:0] tmp_fu_524_p4;
wire   [29:0] tmp_1_fu_540_p4;
wire   [0:0] icmp_fu_534_p2;
wire   [0:0] icmp14_fu_550_p2;
wire   [0:0] or_ln54_1_fu_574_p2;
wire   [0:0] or_ln54_fu_570_p2;
wire   [0:0] or_ln54_2_fu_578_p2;
wire   [0:0] or_ln54_7_fu_584_p2;
wire   [0:0] select_ln29_1_fu_556_p3;
wire   [0:0] valid_fu_595_p2;
wire   [0:0] out_val_V_fu_589_p2;
wire   [0:0] out_data_V_fu_600_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_done_reg = 1'b0;
end

morphology_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter3_stage0)) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_130 <= 64'd0;
        end else if (((icmp_ln29_fu_267_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten_fu_130 <= add_ln29_fu_272_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            reuse_addr_reg19_fu_94 <= 64'd18446744073709551615;
        end else if (((icmp_ln29_fu_267_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            reuse_addr_reg19_fu_94 <= zext_ln30_fu_286_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            reuse_addr_reg_fu_102 <= 64'd18446744073709551615;
        end else if (((icmp_ln29_fu_267_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            reuse_addr_reg_fu_102 <= zext_ln30_fu_286_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reuse_reg18_fu_98 <= 8'd0;
        end else if (((ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln29_reg_721_pp0_iter2_reg == 1'd0))) begin
            reuse_reg18_fu_98 <= reuse_select_reg_763;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reuse_reg_fu_106 <= 8'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln29_reg_721 == 1'd0))) begin
            reuse_reg_fu_106 <= val_V_1_reg_730;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            x_fu_122 <= 9'd0;
        end else if (((icmp_ln29_fu_267_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            x_fu_122 <= add_ln30_fu_349_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            y_fu_126 <= 31'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            y_fu_126 <= select_ln29_2_fu_563_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln29_fu_267_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        addr_cmp22_reg_743 <= addr_cmp22_fu_308_p2;
        addr_cmp_reg_753 <= addr_cmp_fu_317_p2;
        icmp_ln60_reg_758 <= icmp_ln60_fu_343_p2;
        line_buf0_V_addr_reg_737 <= zext_ln30_fu_286_p1;
        tmp_last_V_reg_725 <= in_stream_TLAST;
        val_V_1_reg_730 <= val_V_1_fu_300_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        addr_cmp22_reg_743_pp0_iter2_reg <= addr_cmp22_reg_743;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        icmp_ln1069_6_reg_771_pp0_iter3_reg <= icmp_ln1069_6_reg_771;
        icmp_ln1069_7_reg_776_pp0_iter3_reg <= icmp_ln1069_7_reg_776;
        icmp_ln1069_8_reg_781_pp0_iter3_reg <= icmp_ln1069_8_reg_781;
        icmp_ln29_reg_721_pp0_iter2_reg <= icmp_ln29_reg_721;
        icmp_ln30_reg_715_pp0_iter2_reg <= icmp_ln30_reg_715;
        icmp_ln30_reg_715_pp0_iter3_reg <= icmp_ln30_reg_715_pp0_iter2_reg;
        icmp_ln60_reg_758_pp0_iter2_reg <= icmp_ln60_reg_758;
        icmp_ln60_reg_758_pp0_iter3_reg <= icmp_ln60_reg_758_pp0_iter2_reg;
        line_buf0_V_addr_reg_737_pp0_iter2_reg <= line_buf0_V_addr_reg_737;
        tmp_last_V_reg_725_pp0_iter2_reg <= tmp_last_V_reg_725;
        tmp_last_V_reg_725_pp0_iter3_reg <= tmp_last_V_reg_725_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        icmp_ln29_reg_721 <= icmp_ln29_fu_267_p2;
        icmp_ln30_reg_715 <= icmp_ln30_fu_262_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln29_reg_721_pp0_iter2_reg == 1'd0))) begin
        icmp_ln1069_5_reg_786 <= icmp_ln1069_5_fu_467_p2;
        or_ln54_6_reg_791 <= or_ln54_6_fu_490_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln29_reg_721 == 1'd0))) begin
        icmp_ln1069_6_reg_771 <= icmp_ln1069_6_fu_385_p2;
        icmp_ln1069_7_reg_776 <= icmp_ln1069_7_fu_391_p2;
        icmp_ln1069_8_reg_781 <= icmp_ln1069_8_fu_397_p2;
        reuse_select_reg_763 <= reuse_select_fu_374_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln29_reg_721 == 1'd0))) begin
        p_0_0_072311_fu_118 <= val_V_fu_142;
        val_V_fu_142 <= val_V_1_reg_730;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln29_reg_721_pp0_iter2_reg == 1'd0))) begin
        p_0_0_073310_fu_138 <= reuse_select_reg_763;
        p_0_0_074309_fu_114 <= p_0_0_073310_fu_138;
        p_0_0_075308_fu_134 <= reuse_select23_fu_426_p3;
        p_0_0_076307_fu_110 <= p_0_0_075308_fu_134;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln29_fu_267_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln29_reg_721_pp0_iter2_reg == 1'd1))) begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln29_fu_267_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_stream_TDATA_blk_n = in_stream_TVALID;
    end else begin
        in_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln29_fu_267_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_stream_TREADY = 1'b1;
    end else begin
        in_stream_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        line_buf0_V_ce0 = 1'b1;
    end else begin
        line_buf0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        line_buf0_V_ce1 = 1'b1;
    end else begin
        line_buf0_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln29_reg_721_pp0_iter2_reg == 1'd0))) begin
        line_buf0_V_we0 = 1'b1;
    end else begin
        line_buf0_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln29_fu_267_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buf1_V_ce0 = 1'b1;
    end else begin
        line_buf1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln29_fu_267_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buf1_V_we0 = 1'b1;
    end else begin
        line_buf1_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        out_stream_TDATA_blk_n = out_stream_TREADY;
    end else begin
        out_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        out_stream_TVALID = 1'b1;
    end else begin
        out_stream_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln29_1_fu_518_p2 = (y_fu_126 + 31'd1);

assign add_ln29_fu_272_p2 = (indvar_flatten_fu_130 + 64'd1);

assign add_ln30_fu_349_p2 = (select_ln29_fu_278_p3 + 9'd1);

assign addr_cmp22_fu_308_p2 = ((reuse_addr_reg19_fu_94 == zext_ln30_fu_286_p1) ? 1'b1 : 1'b0);

assign addr_cmp_fu_317_p2 = ((reuse_addr_reg_fu_102 == zext_ln30_fu_286_p1) ? 1'b1 : 1'b0);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((out_stream_TREADY == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((icmp_ln29_fu_267_p2 == 1'd0) & (in_stream_TVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((out_stream_TREADY == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((icmp_ln29_fu_267_p2 == 1'd0) & (in_stream_TVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((out_stream_TREADY == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((icmp_ln29_fu_267_p2 == 1'd0) & (in_stream_TVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((icmp_ln29_fu_267_p2 == 1'd0) & (in_stream_TVALID == 1'b0));
end

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state5_pp0_stage0_iter4 = (out_stream_TREADY == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign icmp14_fu_550_p2 = ((tmp_1_fu_540_p4 != 30'd0) ? 1'b1 : 1'b0);

assign icmp_fu_534_p2 = ((tmp_fu_524_p4 != 30'd0) ? 1'b1 : 1'b0);

assign icmp_ln1069_1_fu_443_p2 = ((p_0_0_075308_fu_134 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln1069_2_fu_449_p2 = ((reuse_select23_fu_426_p3 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln1069_3_fu_455_p2 = ((p_0_0_074309_fu_114 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln1069_4_fu_461_p2 = ((p_0_0_073310_fu_138 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln1069_5_fu_467_p2 = ((reuse_select_reg_763 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln1069_6_fu_385_p2 = ((p_0_0_072311_fu_118 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln1069_7_fu_391_p2 = ((val_V_fu_142 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln1069_8_fu_397_p2 = ((val_V_1_reg_730 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln1069_fu_437_p2 = ((p_0_0_076307_fu_110 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln29_fu_267_p2 = ((indvar_flatten_fu_130 == mul_ln9) ? 1'b1 : 1'b0);

assign icmp_ln30_fu_262_p2 = ((zext_ln30_1_fu_258_p1 == width) ? 1'b1 : 1'b0);

assign icmp_ln60_fu_343_p2 = ((tmp_2_fu_333_p4 != 8'd0) ? 1'b1 : 1'b0);

assign line_buf0_V_address0 = line_buf0_V_addr_reg_737_pp0_iter2_reg;

assign line_buf0_V_address1 = line_buf0_V_addr_reg_737;

assign line_buf0_V_d0 = reuse_select_reg_763;

assign line_buf1_V_address0 = zext_ln30_fu_286_p1;

assign line_buf1_V_d0 = in_stream_TDATA[7:0];

assign or_ln54_1_fu_574_p2 = (icmp_ln1069_6_reg_771_pp0_iter3_reg | icmp_ln1069_5_reg_786);

assign or_ln54_2_fu_578_p2 = (or_ln54_fu_570_p2 | or_ln54_1_fu_574_p2);

assign or_ln54_3_fu_472_p2 = (icmp_ln1069_2_fu_449_p2 | icmp_ln1069_1_fu_443_p2);

assign or_ln54_4_fu_478_p2 = (icmp_ln1069_fu_437_p2 | icmp_ln1069_4_fu_461_p2);

assign or_ln54_5_fu_484_p2 = (or_ln54_4_fu_478_p2 | icmp_ln1069_3_fu_455_p2);

assign or_ln54_6_fu_490_p2 = (or_ln54_5_fu_484_p2 | or_ln54_3_fu_472_p2);

assign or_ln54_7_fu_584_p2 = (or_ln54_6_reg_791 | or_ln54_2_fu_578_p2);

assign or_ln54_fu_570_p2 = (icmp_ln1069_8_reg_781_pp0_iter3_reg | icmp_ln1069_7_reg_776_pp0_iter3_reg);

assign out_data_V_fu_600_p2 = (valid_fu_595_p2 & out_val_V_fu_589_p2);

assign out_stream_TDATA = ((out_data_V_fu_600_p2[0:0] == 1'b1) ? 32'd255 : 32'd0);

assign out_stream_TKEEP = 4'd15;

assign out_stream_TLAST = tmp_last_V_reg_725_pp0_iter3_reg;

assign out_stream_TSTRB = 4'd15;

assign out_val_V_fu_589_p2 = (or_ln54_7_fu_584_p2 ^ 1'd1);

assign reuse_select23_fu_426_p3 = ((addr_cmp22_reg_743_pp0_iter2_reg[0:0] == 1'b1) ? reuse_reg18_fu_98 : line_buf0_V_q1);

assign reuse_select_fu_374_p3 = ((addr_cmp_reg_753[0:0] == 1'b1) ? reuse_reg_fu_106 : line_buf1_V_q0);

assign select_ln29_1_fu_556_p3 = ((icmp_ln30_reg_715_pp0_iter3_reg[0:0] == 1'b1) ? icmp_fu_534_p2 : icmp14_fu_550_p2);

assign select_ln29_2_fu_563_p3 = ((icmp_ln30_reg_715_pp0_iter3_reg[0:0] == 1'b1) ? add_ln29_1_fu_518_p2 : y_fu_126);

assign select_ln29_fu_278_p3 = ((icmp_ln30_fu_262_p2[0:0] == 1'b1) ? 9'd0 : x_fu_122);

assign tmp_1_fu_540_p4 = {{y_fu_126[30:1]}};

assign tmp_2_fu_333_p4 = {{select_ln29_fu_278_p3[8:1]}};

assign tmp_fu_524_p4 = {{add_ln29_1_fu_518_p2[30:1]}};

assign val_V_1_fu_300_p1 = in_stream_TDATA[7:0];

assign valid_fu_595_p2 = (select_ln29_1_fu_556_p3 & icmp_ln60_reg_758_pp0_iter3_reg);

assign zext_ln30_1_fu_258_p1 = x_fu_122;

assign zext_ln30_fu_286_p1 = select_ln29_fu_278_p3;

endmodule //morphology_morphology_Pipeline_VITIS_LOOP_29_1_VITIS_LOOP_30_2
